// try and catch will work on only asynchro function

// setTimeout(()=>{
//     console.log("Hacking UPI Pin please wait...")
// },1000)

// try {
//     console.log(RAhul)
// } catch (error) {
//     console.log("Error")
// }

// setTimeout(()=>{
//     console.log("Fetching Details Wait.")    
// },2000)

// setTimeout(()=>{
//     console.log("UPI Pin is 0000")
// },4000)

// Error Object & Custom Errors
// For all built-in error has two properties :- 1. Error.name , 2. Error.message

// try {
//     hello
// } catch (error) {
//     // console.log(error)
//     console.log(error.name)
//     console.log(error.message)
// }

// let age = 179
// if(age>180){
//     throw new Error("Invalid age")
// }
// else{
//     console.log("Valid age")
// }
// // console.log(age)

// // Finally Clause

// try {
//     console.log(p)
// } catch (error) {
//     console.log("Error")
//     coms  // error
// }

// finally{
//     console.log("This will run not matter what")
// }

setTimeout(()=>{
    console.log("rohan")
},2000)

try{
console.log(ra)
} catch(error){
    // console.log("error")
    kdcn
}

finally{
    console.log("abcd")
}